name: HACS Validation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  hacs-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: HACS Action
        uses: hacs/action@main
