name: Add release file for download in HA into release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v3

      - name: Create zip file
        run: |
          cd custom_components/honda_recall_check
          zip ../../honda_recall_check.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: honda_recall_check.zip
          asset_name: honda_recall_check.zip
          tag: ${{ github.ref }}
          overwrite: true
